# Profile default
server:
  port: 8080
spring:
  application:
    name: app-video
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: ${DATASOURCE_DRIVER}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: "update"
      dialect: "org.hibernate.dialect.MySQL8Dialect"
  servlet:
    multipart:
      enabled: true
      location: /tmp
      max-file-size: 300MB
      max-request-size: 300MB
aws:
  account-id: ${AWS_ACCOUNT_ID}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  bucket-videos: ${AWS_BUCKET_VIDEOS}
  bucket-imagens: ${AWS_BUCKET_IMAGENS}
  bucket-download: ${AWS_BUCKET_DOWNLOAD}
  arn-role-media-convert: ${AWS_ARN_ROLE_MC}
notificacao:
  service:
    url: ${URL_SERV_NOTIFICACAO}

# Profile para a AWS
---
spring:
  config:
    activate:
      on-profile: dev

# Profile para testes
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driverClassName: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:schema-test.sql
      data-locations: classpath:data-test.sql
